modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Lanse505/Essence/issues"

[[mods]]
    modId="essence"
    version="${file.jarVersion}"
    displayName="Essence"
    authors="Lanse505, VeyezX"
    description='''
        Special Thanks to:
            - 2xsaiko
            - Amadornes
            - Drullkus
            - Ellpeck
            - Sekwah
            - Skysom
            - Vazkii
    '''

[[dependencies.essence]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.essence]]
    modId="titanium"
    mandatory=true
    versionRange="[2.3,]"
    ordering="AFTER"
    side="BOTH"